### ISSUE TITLE
ssh2 error

### ISSUE THREAD

**Issue by gianlucaRinaldi** [okomarov/wrds#10]
Hello,
I have a phd WRDS account as well as a JAVA enabled Matlab install (R2015b)
I ran wrds_install() but when I try to connect with 
`
w = wrds('user, 'psw')`

I get the following error:

```
Error: File: ssh2_main.m Line: 21 Column: 8
Arguments to IMPORT must either end with ".*" or else specify a fully qualified class name: "ch.ethz.ssh2.Connection" fails this test.

Error in wrds (line 64)
                obj.SSH2conn = ssh2_main(obj.SSH2conn);
```

Any idea of what's going on?

Thanks!

**Comment by okomarov** [comment]
Can't troubleshoot now, probably just add the .* after the argument of the import statement, without spaces.

Sent from my iPhone

On 27 May 2017, at 18:49, "moritzplatz" <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello,
I have a phd WRDS account as well as a JAVA enabled Matlab install (R2015b)
I ran wrds_install() but when I try to connect with
w = wrds('user, 'psw')

I get the following error:

Error: File: ssh2_main.m Line: 21 Column: 8
Arguments to IMPORT must either end with ".*" or else specify a fully qualified class name: "ch.ethz.ssh2.Connection" fails this test.

Error in wrds (line 64)
                obj.SSH2conn = ssh2_main(obj.SSH2conn);


Any idea of what's going on?

Thanks!

**Comment by gianlucaRinaldi** [comment]
Thanks Oleg for the quick reply. 
I am not sure what caused this, but I just deleted the zip file and downloaded it again at it now works fine!

Thanks again.
