### ISSUE TITLE
passfield submodule not packed into zip

### ISSUE THREAD

**Issue by MrJensen1** [okomarov/wrds#6]
Hello

I have an problem 

Everything works fine until i try to run this command

// Command window // 

> > getdatasetnames(wrds,libref)

Undefined function or variable 'passdlg'.

Error in wrds (line 50)
                tmp      = passdlg('ups');

What can be the problem? 

Thanks!

**Comment by okomarov** [comment]
Hi, I forgot to specify in the readme, to run `wrds_install()` first, if you haven't yet. Then after that, check that `path()` has a path that ends with `./external/passfield`.

**Comment by MrJensen1** [comment]
Thanks for the quick reply!

There is not any path that ends with

./external/passfield.

I only have:

```
C:\Program Files\MATLAB\R2015b\toolbox\matlab\external\interfaces\webservices\restful
C:\Program Files\MATLAB\R2015b\toolbox\matlab\external\interfaces
C:\Program Files\MATLAB\R2015b\toolbox\matlab\external\interfaces\webservices
C:\Program Files\MATLAB\R2015b\toolbox\matlab\external\interfaces\webservices\wsdl
```

Do you have any suggestion what to do?

THANKS!

**Comment by okomarov** [comment]
I identified the issue, the `passfield()` is included in the repo as a submodule, which is not packed into the distributed .zip. I am looking into it.

**Comment by MrJensen1** [comment]
Thanks :).

**Comment by okomarov** [comment]
A quick fix, is to manually download and unpack the content of https://github.com/okomarov/passfield into the `external/passfield` folder, and then run `wrds_install()` once more. 

I will work on a solution that automates this problem since Github does not include submodules into the .zip (no setting that would include it automatically either).

**Comment by okomarov** [comment]
The https://github.com/okomarov/wrds/commit/ce6f76ba1f04de0547610c5169f2e0e140b4e2b7 should have fixed the issue. Please try to download the zip again, and runt wrds_install.

**Comment by okomarov** [comment]
I assume the problem has been solved and will be closing the issue. Please, feel free to re-open in case the problem persists.
